# Generated by Django 4.0.3 on 2022-03-14 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_menuitem_type'),
        ('accounts', '0002_user_phone_alter_user_avatar_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
