# Generated by Django 4.0.3 on 2022-03-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_ownernotification_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantupdate',
            old_name='time',
            new_name='datetime',
        ),
    ]
