# Generated by Django 4.0.3 on 2022-03-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_rename_time_restaurantupdate_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantupdate',
            old_name='datetime',
            new_name='last_modified',
        ),
    ]
