# Generated by Django 4.0.3 on 2022-03-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_description_alter_restaurant_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownernotification',
            old_name='time',
            new_name='last_modified',
        ),
    ]
