# Generated by Django 4.0.3 on 2022-03-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_rename_time_ownernotification_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
