# Generated by Django 4.0.3 on 2022-03-15 16:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='carousel_img_1',
            field=models.ImageField(blank=True, default='Restaurant/Carousel/image.png', null=True, upload_to='Restaurants/Carousel/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='carousel_img_2',
            field=models.ImageField(blank=True, default='Restaurant/Carousel/image.png', null=True, upload_to='Restaurants/Carousel/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='carousel_img_3',
            field=models.ImageField(blank=True, default='Restaurant/Carousel/image.png', null=True, upload_to='Restaurants/Carousel/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_img',
            field=models.ImageField(blank=True, default='Restaurant/Cover/image.png', null=True, upload_to='Restaurants/Cover/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_1',
            field=models.ImageField(blank=True, default='Restaurant/Image/image.png', null=True, upload_to='Restaurants/Image/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_2',
            field=models.ImageField(blank=True, default='Restaurant/Image/image.png', null=True, upload_to='Restaurants/Image/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_3',
            field=models.ImageField(blank=True, default='Restaurant/Image/image.png', null=True, upload_to='Restaurants/Image/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_4',
            field=models.ImageField(blank=True, default='Restaurant/Image/image.png', null=True, upload_to='Restaurants/Image/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='restaurants.restaurant'),
        ),
    ]
