# Generated by Django 4.0.3 on 2022-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_carousel_img_1_restaurant_carousel_img_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantnotification',
            name='type',
            field=models.CharField(default='RANDOM STUFF DUE TO UPDATE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantnotification',
            name='type_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
