# Generated by Django 4.0.3 on 2022-04-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantnotification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownernotification',
            name='type',
            field=models.CharField(default='IDEK FIX DUE TO TYPE UPDATE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownernotification',
            name='type_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
