# Generated by Django 4.0.3 on 2022-03-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_bloglike_delete_bloglikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='Blogs/Post/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='Blogs/Post/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='Blogs/Post/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='primary_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Blogs/Post/'),
        ),
    ]
